apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-cluster
  namespace: elastic-system
spec:
  version: 8.12.2
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 60Gi
        storageClassName: nfs-client
          #    podTemplate:
          #      spec:
          #        containers:
          #        - name: elasticsearch
          #          resources:
          #            requests:
          #              memory: "512Mi"
          #            limits:
          #              memory: "512Mi"
