apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: elastic-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  storageClassName: nfs-client
